## Numpy array and basics

In [2]:
import numpy as np

## Creating array from list

In [5]:
arr_1d = np.array([1,2,3,4,5,6])
print("1D array", arr_1d)

arr_2d = np.array([[1,2,3],[4,5,6]])
print("2D array", arr_2d)

1D array [1 2 3 4 5 6]
2D array [[1 2 3]
 [4 5 6]]


## List vs numpy array

In [11]:
py_list = [1, 2, 3]
print("Python List multiplication", py_list * 2)

np_arr = np.array([1, 2, 3]) #element wise multiplication
print("Python numpy array multiplication", np_arr * 2)


import time

start = time.time()
py_list = [i * 2 for i in range(10000000)]
print("\n List operation time:", time.time() - start)

start = time.time()
np_arr = np.arange(10000000) * 2
print("\n Numpy operation time:", time.time() - start)




Python List multiplication [1, 2, 3, 1, 2, 3]
Python numpy array multiplication [2 4 6]

 List operation time: 1.4958131313323975

 Numpy operation time: 0.09723377227783203


## Creating array from zeroes or ones (Matrices)

In [17]:
zeroes = np.zeros((3, 4))

print("Zeroes Array", zeroes)

ones = np.ones((3, 4))

print("1 Array", ones)

full = np.full((2,2), 7)
print("Constant value array", full)

random = np.random.random((2, 3))
print("Random Array", random)

sequence = np.arange(0, 20, 2)
print("Sequence Array:","\n", sequence)

Zeroes Array [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
1 Array [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Constant value array [[7 7]
 [7 7]]
Random Array [[0.44728234 0.35160701 0.80991823]
 [0.73794087 0.62322328 0.63774876]]
Sequence Array: 
 [ 0  2  4  6  8 10 12 14 16 18]


### Vector, Matrices and Tensor

In [19]:
vector = np.array([1,2,3,])
print("Vector: ", vector)

matrices = np.array([[1,2,3],[4,5,6]])
print("Matrices: ", matrices)

tensor = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print("Tensor: ", tensor)

Vector:  [1 2 3]
Matrices:  [[1 2 3]
 [4 5 6]]
Tensor:  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array Properties

In [ ]:
arr  = np.array([[1, 2, 3], [4, 5, 6], [6, 7, 8]])

print("Shape of Array ", arr.shape)
print("Dimension", arr.ndim)
print("Size (total element in array)", arr.size)
print("Data type ", arr.dtype) 


Shape of Array  (3, 3)
Dimension (no of rows) 2
Size (total element in array) 9
Data type  int64


### Array Reshaping

In [3]:
arr = np.arange(12)
print("Original Array ", arr)

reshaped = arr.reshape((3, 4))
print("\n Reshaped Array ", reshaped)


flattened = reshaped.flatten()
print("\n Flatten Array ", flattened)

#ravel (returns view, instead of copy)
raveled = reshaped.ravel()
print("\n Ravel Array ", raveled)

#Transpose
transpose = reshaped.T
print("\n Transpose Array ", transpose)


Original Array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshaped Array  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flatten Array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Ravel Array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Transpose Array  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
