## Numpy Array Operations

In [14]:
import numpy as np

In [15]:
arr = np.array([1,2,3,4,5,6,7,8,9, 10])

print("Basic Slicing", arr[2:7])

print("With Steps", arr[1:8:2])
print("Negative Indexing", arr[-3])

Basic Slicing [3 4 5 6 7]
With Steps [2 4 6 8]
Negative Indexing 8


In [16]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

print("Specific Element", arr_2d[1,2])
print("Entire Row: ", arr_2d[1])
print("Entire Column: ", arr_2d[:,1])

Specific Element 6
Entire Row:  [4 5 6]
Entire Column:  [2 5 8]


### Sorting

In [24]:
unsorted = np.array([2,3,1,5,7,9,8,4,6])
unsorted.sort()
print("Sort", unsorted)
print("Sort # 2", np.sort(unsorted))

arr_2d_unsorted = np.array([[3,1],[1,2],[2,3]])
print("Sorted 2D array by column", np.sort(arr_2d_unsorted, axis=0))
print("Sorted 2D array by row", np.sort(arr_2d_unsorted, axis=1))


Sort [1 2 3 4 5 6 7 8 9]
Sort # 2 [1 2 3 4 5 6 7 8 9]
Sorted 2D array by column [[1 1]
 [2 2]
 [3 3]]
Sorted 2D array by row [[1 3]
 [1 2]
 [2 3]]


## Filter

In [29]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])

even_numbers = numbers[numbers % 2 == 0]

print("Even numbers", even_numbers)

Even numbers [ 2  4  6  8 10]


## Filter with mask

In [32]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])

mask = numbers > 5

print("Numbers greater than 5 ", numbers[mask])

Numbers greater than 5  [ 6  7  8  9 10]


##  Fancy Indexing vs np.where()

In [36]:
indices = [0, 2, 4]
print(numbers[indices])
print(numbers[[0, 2, 4]]) #We can get multiple element from list by passing multiple index


where_result = np.where(numbers > 5)

print(where_result) # It will give indexes of value whose value will be greater than 5

print("NP Where Result", numbers[where_result])



[1 3 5]
[1 3 5]
(array([5, 6, 7, 8, 9]),)
NP Where Result [ 6  7  8  9 10]


In [38]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])

condition_array = np.where(numbers > 5, numbers + 2, numbers - 2)
# if( numbers > 5) {
#    numbers + 2
# } else {
#    numbers - 2
# }

print("Condition Array", condition_array)

Condition Array [-1  0  1  2  3  8  9 10 11 12]


### Adding and removing data and combining data

In [41]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

combined = np.concatenate((arr1, arr2))

print(combined)

[1 2 3 4 5 6]


### Array Compatibility 

In [47]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6, 7])
c = np.array([7, 8, 9])

print("Compatibility Shapes", c.shape == b.shape)




Compatibility Shapes False


In [53]:
original = np.array([[1,2],[3,4]])

new_row = np.array([[5, 6]])

with_new_row = np.vstack((original, new_row)) # vstack add new row
print("Original")
print(original)
print("With New Row")
print(with_new_row)

new_col = np.array([[7],[8]])

with_new_col = np.hstack((original, new_col))
print("With New Col")
print(with_new_col)



Original
[[1 2]
 [3 4]]
With New Row
[[1 2]
 [3 4]
 [5 6]]
With New Col
[[1 2 7]
 [3 4 8]]


## Delete from Array

In [59]:
arr = np.array([1,2,3,4,5,6,7,8])

deleted = np.delete(arr, (2,5,6))

print("Deleted Array", deleted)


Deleted Array [1 2 4 5 8]
