### 1. Array Creation & Operations

Create a NumPy array containing the numbers from 1 to 10.

Find the sum of all numbers.
Find the average.
Find the maximum and minimum values.
Multiply every element by 2.

In [12]:
import numpy as np

arr = np.arange(1, 11)
print("Array from 1 to 10: ", arr)
print("Sum of all numbers: ", np.sum(arr, axis = 0))
print("Average of all numbers: ", np.mean(arr, axis = 0))
print("Minimum number: ", np.min(arr, axis = 0))
print("Maximum number: ", np.max(arr, axis = 0))
print("Multiply every element by 2: ", arr * 2)





Array from 1 to 10:  [ 1  2  3  4  5  6  7  8  9 10]
Sum of all numbers:  55
Average of all numbers:  5.5
Minimum number:  1
Maximum number:  10
Multiply every element by 2:  [ 2  4  6  8 10 12 14 16 18 20]


### 2. numbers = np.array([12, 5, 8, 21, 7, 30, 15, 3])

Write NumPy code to:

Find all numbers greater than 10.
Find all even numbers.
Replace all numbers less than 10 with 0.

In [15]:
numbers = np.array([12, 5, 8, 21, 7, 30, 15, 3])

print("Find all numbers greater than 10: ", numbers[np.where(numbers > 10)])
print("Find all even numbers: ", numbers[np.where(numbers % 2 == 0)])
print("Find all even numbers: ", np.where(numbers < 10, 0, numbers))


Find all numbers greater than 10:  [12 21 30 15]
Find all even numbers:  [12  8 30]
Find all even numbers:  [12  0  0 21  0 30 15  0]


### 3. Create this NumPy array:
10  20  30
40  50  60
70  80  90

Find the shape of the array.
Find the sum of each row.
Find the sum of each column.
Extract the second row.
Extract the last column.

In [26]:
arr = np.array([
[10,  20,  30],
[40,  50,  60],
[70,  80,  90]])

print("2D Array: \n", arr)
print("Shape of the Array: \n", arr.shape)
print("Sum of each row: \n", np.sum(arr, axis=1))
print("Sum of each column: \n", np.sum(arr, axis=0))
print("Second Row: \n", arr[1])
print("Second Row: \n", arr[:, -1:])




2D Array: 
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
Shape of the Array: 
 (3, 3)
Sum of each row: 
 [ 60 150 240]
Sum of each column: 
 [120 150 180]
Second Row: 
 [40 50 60]
Second Row: 
 [[30]
 [60]
 [90]]


### 4. String Array & Vectorization
Using np.vectorize():

Replace every "a" with "*".
Convert every restaurant name to uppercase.
Add " Restaurant" to the end of every name.

In [33]:
restaurants = np.array([
    "biryani",
    "pizza",
    "burger",
    "bbq",
    "cafe",
    "chinese"
])

vectorize_char = np.vectorize(lambda s: s.replace("a", "*"))
print("Replace every 'a' with '*' : \n", vectorize_char(restaurants))

vectorize_upper = np.vectorize(str.upper)
print("Convert every restaurant name to uppercase : \n", vectorize_upper(restaurants))

vectorize_add_word = np.vectorize(lambda s: f"{s.capitalize()} Restaurant")
print("Add 'Restaurant to the end of every name' : \n", vectorize_add_word(restaurants))



Replace every 'a' with '*' : 
 ['biry*ni' 'pizz*' 'burger' 'bbq' 'c*fe' 'chinese']
Convert every restaurant name to uppercase : 
 ['BIRYANI' 'PIZZA' 'BURGER' 'BBQ' 'CAFE' 'CHINESE']
Add 'Restaurant to the end of every name' : 
 ['Biryani Restaurant' 'Pizza Restaurant' 'Burger Restaurant'
 'Bbq Restaurant' 'Cafe Restaurant' 'Chinese Restaurant']


### 5. Challenge — Student Marks

Calculate each student's total marks.
Calculate each student's average.
Find the student with the highest average.
Find the highest mark in each subject.
Find students whose average is 70 or above.

In [44]:
marks = np.array([
    [80, 75, 90],
    [60, 65, 70],
    [95, 88, 92],
    [45, 55, 50]
])

print("\n Calculate each student's total marks: \n", np.sum(marks, axis=1))
print("\n Calculate each student's average: \n", np.mean(marks, axis=1))
print("\n Find the student with the highest average: \n", np.max(np.mean(marks, axis=0), axis=0))
print("\n Find the student with the highest average: \n", np.max(marks, axis=0))
print("\n Find the student whose average is 70 or above: \n", marks[np.where(np.mean(marks, axis=1) >= 70)])



 Calculate each student's total marks: 
 [245 195 275 150]

 Calculate each student's average: 
 [81.66666667 65.         91.66666667 50.        ]

 Find the student with the highest average: 
 75.5

 Find the student with the highest average: 
 [95 88 92]

 Find the student whose average is 70 or above: 
 [[80 75 90]
 [95 88 92]]
